### ISSUE TITLE
gprestore not support parallel restoration of indexes

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpbackup#494] opened 2021-05-05 15:15 UTC
In the process of restoring data using gprestore, when the `jobs` option is specified, the tablespace setting of the index may be incorrect when the index is rebuilt.

```
$ gprestore --plugin-config /opt/greenplum/config/s3_backup.yml --timestamp 20210430155944 --create-db --jobs 4 --on-error-continue
...
20210502:09:48:33 gprestore:gpadmin:gp6mdw:029875-[INFO]:-Restoring post-data metadata
20210502:09:51:02 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Post-data objects restored:  10% (41/404)
20210502:10:09:55 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Post-data objects restored:  20% (81/404)
20210502:10:10:16 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Post-data objects restored:  30% (122/404)
20210502:10:10:16 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Post-data objects restored:  30% (123/404)
20210502:10:10:34 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Post-data objects restored:  50% (202/404)
20210502:10:10:43 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Post-data objects restored:  60% (243/404)
20210502:10:11:03 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Post-data objects restored:  70% (283/404)
20210502:10:11:20 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Error encountered when executing statement: ALTER INDEX dw.idx_dw_fact_cpu_sno_parts_sno SET TABLESPACE tbs_ssd01; Error was: ERROR: relation "dw.idx_dw_fact_cpu_sno_parts_sno" does not exist (SQLSTATE 42P01)
20210502:10:11:28 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Error encountered when executing statement: ALTER INDEX dw.idx_dw_fact_cpu_sn_sno SET TABLESPACE tbs_ssd01; Error was: ERROR: relation "dw.idx_dw_fact_cpu_sn_sno" does not exist (SQLSTATE 42P01)
20210502:10:11:52 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Post-data objects restored:  80% (324/404)
20210502:10:11:52 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Error encountered when executing statement: ALTER INDEX dw.idx_dw_fact_pca_rep_mcbsno SET TABLESPACE tbs_ssd01; Error was: ERROR: relation "dw.idx_dw_fact_pca_rep_mcbsno" does not exist (SQLSTATE 42P01)
20210502:10:12:09 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Error encountered when executing statement: ALTER INDEX dw.idx_dw_fact_sn_info_orig_mcbsno SET TABLESPACE tbs_ssd01; Error was: ERROR: relation "dw.idx_dw_fact_sn_info_orig_mcbsno" does not exist (SQLSTATE 42P01)
20210502:10:13:33 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Error encountered when executing statement: ALTER INDEX dwfqas.idx_dwfqas_fact_fqas_lr_sn_mcbsno SET TABLESPACE tbs_ssd01; Error was: ERROR: relation "dwfqas.idx_dwfqas_fact_fqas_lr_sn_mcbsno" does not exist (SQLSTATE 42P01)
20210502:10:13:33 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Error encountered when executing statement: ALTER INDEX dwfqas.idx_dwfqas_fact_fqas_lr_sn_old_sn SET TABLESPACE tbs_ssd01; Error was: ERROR: relation "dwfqas.idx_dwfqas_fact_fqas_lr_sn_old_sn" does not exist (SQLSTATE 42P01)
20210502:10:13:33 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Error encountered when executing statement: ALTER INDEX dwfqas.idx_dwfqas_fact_fqas_lr_sn_orgmcbsno SET TABLESPACE tbs_ssd01; Error was: ERROR: relation "dwfqas.idx_dwfqas_fact_fqas_lr_sn_orgmcbsno" does not exist (SQLSTATE 42P01)
20210502:10:13:36 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Error encountered when executing statement: ALTER INDEX dwfqas.idx_dwfqas_fact_fqas_pca_sn_customer SET TABLESPACE tbs_ssd01; Error was: ERROR: relation "dwfqas.idx_dwfqas_fact_fqas_pca_sn_customer" does not exist (SQLSTATE 42P01)
20210502:10:13:36 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Error encountered when executing statement: ALTER INDEX dwfqas.idx_dwfqas_fact_fqas_pca_sn_family SET TABLESPACE tbs_ssd01; Error was: ERROR: relation "dwfqas.idx_dwfqas_fact_fqas_pca_sn_family" does not exist (SQLSTATE 42P01)
20210502:10:13:44 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Error encountered when executing statement: ALTER INDEX dwfqas.idx_dwfqas_fact_fqas_pca_sn_invoice SET TABLESPACE tbs_ssd01; Error was: ERROR: relation "dwfqas.idx_dwfqas_fact_fqas_pca_sn_invoice" does not exist (SQLSTATE 42P01)
20210502:10:13:51 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Error encountered when executing statement: ALTER INDEX dwfqas.idx_dwfqas_fact_fqas_pca_sn_mcbsno SET TABLESPACE tbs_ssd01; Error was: ERROR: relation "dwfqas.idx_dwfqas_fact_fqas_pca_sn_mcbsno" does not exist (SQLSTATE 42P01)
20210502:10:13:51 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Error encountered when executing statement: ALTER INDEX dwfqas.idx_dwfqas_fact_fqas_pca_sn_model SET TABLESPACE tbs_ssd01; Error was: ERROR: relation "dwfqas.idx_dwfqas_fact_fqas_pca_sn_model" does not exist (SQLSTATE 42P01)
20210502:10:13:54 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Error encountered when executing statement: ALTER INDEX dwfqas.idx_dwfqas_fact_fqas_pca_sn_orgdn SET TABLESPACE tbs_ssd01; Error was: ERROR: relation "dwfqas.idx_dwfqas_fact_fqas_pca_sn_orgdn" does not exist (SQLSTATE 42P01)
20210502:10:14:00 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Error encountered when executing statement: ALTER INDEX dwfqas.idx_dwfqas_fact_fqas_pca_sn_orgmcbsno SET TABLESPACE tbs_ssd01; Error was: ERROR: relation "dwfqas.idx_dwfqas_fact_fqas_pca_sn_orgmcbsno" does not exist (SQLSTATE 42P01)
20210502:10:14:08 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Post-data objects restored:  90% (364/404)
20210502:10:14:21 gprestore:gpadmin:gp6mdw:029875-[DEBUG]:-Error encountered when executing statement: ALTER INDEX dwfqas.idx_dwfqas_fact_pca_sn_carton SET TABLESPACE tbs_ssd01; Error was: ERROR: relation "dwfqas.idx_dwfqas_fact_pca_sn_carton" does not exist (SQLSTATE 42P01)
20210502:10:15:59 gprestore:gpadmin:gp6mdw:029875-[ERROR]:-Encountered 15 errors during metadata restore; see log file /home/gpadmin/gpAdminLogs/gprestore_20210502.log for a list of failed statements.
20210502:10:15:59 gprestore:gpadmin:gp6mdw:029875-[INFO]:-Post-data metadata restore complete
...
```

**Comment by jimmyyih** [comment] 2021-05-06 03:54
Hello, thanks for reporting this.  I am able to reproduce the issue.  The issue occurs when a table has multiple indexes and are on user-defined tablespaces (other ALTER INDEX commands might have this issue too).  One of the job workers could be running the CREATE INDEX (which can take a long time) while another concurrent job worker is running the ALTER INDEX (which fails because the index hasn't been created yet).  We'll look into how to fix this (I think we just need to associate the ALTER INDEX with the CREATE INDEX which seems to be missing).

As a workaround for now, the ALTER INDEX SET TABLESPACE commands that failed can be run manually after gprestore completes.

**Comment by cobolbaby** [comment] 2021-05-06 06:41
Waiting for good news.

**Comment by jimmyyih** [comment] 2021-06-04 03:35
Fixed with https://github.com/greenplum-db/gpbackup/commit/4f79e0e68156852ba903b3f875c9d4a882feb7ba.  Thanks for the report!

**Closed** 2021-06-04 03:35 UTC
