### ISSUE TITLE
NoSuchKey: The specified key does not exist

### ISSUE THREAD

**Issue by cobolbaby** [greenplum-db/gpbackup#499] opened 2021-05-17 06:36 UTC
- gpbackup exception:

```
20210516:20:04:54 gpbackup:gpadmin:gp6mdw:036189-[DEBUG]:-Worker 2: COPY fis.pca_pca_model_change_log TO PROGRAM 'gzip -c -1 | /usr/local/greenplum-db-6.16.0/bin/gpbackup_s3_plugin backup_data /tmp/20210516200002_s3_backup.yml <SEG_DATA_DIR>/backups/20210516/20210516200002/gpbackup_<SEGID>_20210516200002_864333.gz' WITH CSV DELIMITER ',' ON SEGMENT IGNORE EXTERNAL PARTITIONS;
20210516:20:06:35 gpbackup:gpadmin:gp6mdw:036189-[CRITICAL]:-ERROR: command error message: 20210516:20:05:22 gpbackup_s3_plugin:gpadmin:gp6sdw5:011663-[ERROR]:-NoSuchKey: The specified key does not exist.
        status code: 404, request id: 167F8A84E7318F00, host id:  (seg16 10.13.0.63:40000 pid=508) (SQLSTATE 2F000)
github.com/greenplum-db/gpbackup/backup.backupDataForAllTables
        /tmp/build/3e49593f/go/src/github.com/greenplum-db/gpbackup/backup/data.go:223
github.com/greenplum-db/gpbackup/backup.backupData
        /tmp/build/3e49593f/go/src/github.com/greenplum-db/gpbackup/backup/backup.go:280
github.com/greenplum-db/gpbackup/backup.DoBackup
        /tmp/build/3e49593f/go/src/github.com/greenplum-db/gpbackup/backup/backup.go:160
main.main.func1
        /tmp/build/3e49593f/go/src/github.com/greenplum-db/gpbackup/gpbackup.go:23
github.com/spf13/cobra.(*Command).execute
        /tmp/build/3e49593f/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830
github.com/spf13/cobra.(*Command).ExecuteC
        /tmp/build/3e49593f/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /tmp/build/3e49593f/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
        /tmp/build/3e49593f/go/src/github.com/greenplum-db/gpbackup/gpbackup.go:27
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```

- pg_log:

```
2021-05-16 20:05:22.268876 CST,"gpadmin","F6_BDC",p508,th-2048743296,"10.13.0.65","55388",2021-05-16 20:00:02 CST,0,con1347551,cmd98,seg16,,dx23343414,,sx1,"LOG","00000","read err msg from pipe, len:173 msg:20210516:20:05:22 gpbackup_s3_plugin:gpadmin:gp6sdw5:011663-[ERROR]:-NoSuchKey: The specified key does not exist.
        status code: 404, request id: 167F8A84E7318F00, host id:
",,,,,,,0,,,,
```

**Comment by jimmyyih** [comment] 2021-05-19 00:09
Hi,

That's an interesting error... just for context, could you check some things:
1. Was there a successful COPY for another table in the gpbackup log?  This is to confirm that only this table had issues backing up or if there were others as well.
2. On host `10.13.0.63` which seg16 belongs to (the segment that gave the error message), do you see an S3 plugin log file in `~/gpAdminLogs/`?  If so, could you check the log for relevant error messages and the sequence of events surrounding that error message?  Or upload the S3 log file to this Github issue thread and we could take a look.  This is to figure out where the S3 plugin was at in its logic execution when the error occurred.
3. Could you go through the debugging steps outlined in https://aws.amazon.com/premiumsupport/knowledge-center/404-error-nosuchkey-s3/.  The steps make more sense for gprestore than gpbackup... but it's worth taking a look.  Are you able to see a path similar to `*/20210516/20210516200002/*` in your S3 bucket?
4. Did a previous gpbackup to the same S3 bucket fail recently or right before that gpbackup run?  Or do you have some S3 cleanup job?  This is to see if the path was deleted in the middle of the gpbackup execution.
5. Has this happened multiple times or just the one time?

Sorry if that's a lot of things to check.  This is a very unexpected error and it would be great to find the root cause.

**Comment by cobolbaby** [comment] 2021-05-19 04:20
> Was there a successful COPY for another table in the gpbackup log? This is to confirm that only this table had issues backing up or if there were others as well.

The problem happens occasionally and is not targeted.

> On host 10.13.0.63 which seg16 belongs to (the segment that gave the error message), do you see an S3 plugin log file in ~/gpAdminLogs/? If so, could you check the log for relevant error messages and the sequence of events surrounding that error message? Or upload the S3 log file to this Github issue thread and we could take a look. This is to figure out where the S3 plugin was at in its logic execution when the error occurred.

```
20210516:20:05:22 gpbackup_s3_plugin:gpadmin:gp6sdw5:011664-[ERROR]:-NoSuchKey: The specified key does not exist.
        status code: 404, request id: 167F8A84E646404C, host id:
20210516:20:05:22 gpbackup_s3_plugin:gpadmin:gp6sdw5:011663-[ERROR]:-NoSuchKey: The specified key does not exist.
        status code: 404, request id: 167F8A84E7318F00, host id:
```

[gpbackup_s3_plugin_20210516.log](https://github.com/greenplum-db/gpbackup/files/6505815/gpbackup_s3_plugin_20210516.log)

> Has this happened multiple times or just the one time?

Multiple times.

**Comment by cobolbaby** [comment] 2021-05-19 04:27
> Could you go through the debugging steps outlined in https://aws.amazon.com/premiumsupport/knowledge-center/404-error-nosuchkey-s3/. The steps make more sense for gprestore than gpbackup... but it's worth taking a look. Are you able to see a path similar to */20210516/20210516200002/* in your S3 bucket?

![2021-05-19 12-24-20屏幕截图](https://user-images.githubusercontent.com/11460848/118756321-3ac07600-b89d-11eb-90d0-11e139878136.png)

> Did a previous gpbackup to the same S3 bucket fail recently or right before that gpbackup run? Or do you have some S3 cleanup job? This is to see if the path was deleted in the middle of the gpbackup execution.

- It's all right before that gpbackup run. 
- I do not have the clean job.

**Comment by kyeap-vmware** [comment] 2022-01-22 01:52
While we can't confirm this is your issues without more details. It's possible for the `NoSuchKey` error to occur when trying to query an object that was just uploaded. This is due to the nature of MinIO or AWS's eventual consistency. If this is indeed the issue it may be resolved with s3-plugin's recent commit which implements a retry mechanism for such cases. s3-plugin retry commit https://github.com/greenplum-db/gpbackup-s3-plugin/commit/7ed84b11f1c196a7c9d0f6a57c835a03a82b00d7

**Closed by kyeap-vmware** 2022-01-22 01:52 UTC
